import express from "express";
import cors from "cors";
import multer from "multer";
import sqlite3 from "sqlite3";
import dotenv from "dotenv";
import fs from "fs";
import path from "path";
import OpenAI from "openai";
import { fileURLToPath } from "url";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 4000;

app.use(cors());
app.use(express.json());

const upload = multer({ dest: path.join(__dirname, "uploads/") });

const dbPath = path.join(__dirname, "resly.db");
const db = new sqlite3.Database(dbPath);

db.serialize(() => {
  db.run(`
    CREATE TABLE IF NOT EXISTS generations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      role TEXT,
      jd TEXT,
      resume_filename TEXT,
      used_ai INTEGER,
      output_length INTEGER
    )
  `);
});

let openai = null;
if (process.env.OPENAI_API_KEY && process.env.OPENAI_API_KEY.trim() !== "") {
  openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
}

function simpleGenerator(resumeText, jdText, role) {
  return `
Tailored Resume (Simple Mode)
=============================

Target Role: ${role || "Not specified"}

-------------------------
SUMMARY (AUTOGENERATED)
-------------------------
This resume was quickly tailored using Resly's simple engine.
The content below is based on your original resume and the job description.

-------------------------
ORIGINAL RESUME (SNIPPET)
-------------------------
${resumeText.slice(0, 1500)}

-------------------------
JOB DESCRIPTION (SNIPPET)
-------------------------
${jdText.slice(0, 1500)}

  `.trim();
}

function readUploadedFile(file) {
  return fs.readFileSync(file.path, "utf8").toString();
}

app.get("/api/health", (req, res) => {
  res.json({ ok: true, message: "Resly backend running" });
});

app.post(
  "/api/generate",
  upload.single("resume"),
  async (req, res) => {
    try {
      const jd = req.body.jd || "";
      const role = req.body.role || "";
      const resumeFile = req.file;

      if (!jd || !resumeFile) {
        return res.status(400).json({ error: "Missing resume or JD." });
      }

      let resumeText = "";
      try {
        resumeText = readUploadedFile(resumeFile);
      } catch {
        resumeText = "Could not read resume contents.";
      }

      let usedAI = 0;
      let tailoredText = "";

      if (openai) {
        try {
          const prompt = `
Rewrite this resume to match this job description.

RESUME:
${resumeText}

JOB DESCRIPTION:
${jd}

ROLE: ${role}
`;
          const completion = await openai.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [
              { role: "system", content: "You are a professional resume writer." },
              { role: "user", content: prompt }
            ],
            temperature: 0.3
          });

          tailoredText = completion.choices[0].message.content.trim();
          usedAI = 1;
        } catch {
          tailoredText = simpleGenerator(resumeText, jd, role);
        }
      } else {
        tailoredText = simpleGenerator(resumeText, jd, role);
      }

      db.run(
        `INSERT INTO generations (role, jd, resume_filename, used_ai, output_length)
         VALUES (?, ?, ?, ?, ?)`,
        [role, jd.slice(0,2000), resumeFile.originalname, usedAI, tailoredText.length]
      );

      fs.unlink(resumeFile.path, () => {});
      res.json({ ok: true, usedAI: usedAI === 1, tailoredResume: tailoredText });

    } catch (error) {
      res.status(500).json({ error: "Internal server error" });
    }
  }
);

app.listen(PORT, () => {
  console.log(`Resly backend running on http://localhost:${PORT}`);
});
